create or replace function public.report_breakdown(p_machine_id uuid,p_reason text,p_notes text default '',p_assigned_to uuid default null) returns uuid language plpgsql security definer set search_path to 'public' as $$ declare bid uuid; b public.breakdowns; begin if not exists(select 1 from public.profiles where id=auth.uid() and active) then raise exception 'Active user required'; end if; if trim(coalesce(p_reason,''))='' then raise exception 'Breakdown reason is required'; end if; if not exists(select 1 from public.machines where id=p_machine_id and active) then raise exception 'Active machine not found'; end if; if p_assigned_to is null or not exists(select 1 from public.profiles where id=p_assigned_to and active) then raise exception 'A valid active assigned employee is required'; end if; select * into b from public.breakdowns where machine_id=p_machine_id and resolved_at is null for update; if found then raise exception 'This machine already has an open breakdown'; end if; insert into public.breakdowns(machine_id,reason,notes,reported_by,assigned_to) values(p_machine_id,trim(p_reason),coalesce(p_notes,''),auth.uid(),p_assigned_to) returning * into b; update public.machines set status='breakdown'::public.machine_status,last_confirmed_at=now() where id=p_machine_id; insert into public.audit_log(actor_id,action,entity_type,entity_id,details) values(auth.uid(),'report_breakdown','breakdown',b.id,jsonb_build_object('machine_id',p_machine_id,'reason',trim(p_reason),'assigned_to',p_assigned_to)); return b.id; end; $$;

create table if not exists public.breakdown_media(id uuid primary key default gen_random_uuid(),breakdown_id uuid not null references public.breakdowns(id) on delete cascade,storage_path text not null,original_name text,content_type text,created_at timestamptz not null default now(),uploaded_by uuid references public.profiles(id));
create index if not exists breakdown_media_breakdown_id_idx on public.breakdown_media(breakdown_id);
alter table public.breakdown_media enable row level security;
drop policy if exists breakdown_media_select_auth on public.breakdown_media;
drop policy if exists breakdown_media_insert_auth on public.breakdown_media;
create policy breakdown_media_select_auth on public.breakdown_media for select to authenticated using (true);
create policy breakdown_media_insert_auth on public.breakdown_media for insert to authenticated with check (uploaded_by = auth.uid());

create or replace function public.create_machine(p_name text,p_fleet_id text,p_model text,p_site text,p_hours numeric,p_status text,p_service_interval_hours numeric,p_service_warning_hours numeric) returns public.machines language plpgsql security definer set search_path to 'public' as $$ declare r public.machines; begin if not public.is_manager() then raise exception 'Management permission required'; end if; if p_status not in ('working','available','breakdown','maintenance','offline') then raise exception 'Invalid machine status'; end if; insert into public.machines(name,fleet_id,model,site,hours,status,service_interval_hours,service_warning_hours,active,last_confirmed_at) values(trim(p_name),trim(p_fleet_id),coalesce(p_model,''),coalesce(p_site,''),coalesce(p_hours,0),p_status::public.machine_status,coalesce(p_service_interval_hours,500),coalesce(p_service_warning_hours,50),true,now()) returning * into r; insert into public.audit_log(actor_id,action,entity_type,entity_id,details) values(auth.uid(),'create_machine','machine',r.id,jsonb_build_object('fleet_id',r.fleet_id,'status',r.status)); return r; end; $$;